Traceback (most recent call last):
  File "sg_main.py", line 85, in <module>
    results = sg_model.main(settings, params)
  File "/nobackup/py13jh/dispersal_model/sgm_model/sg_model.py", line 325, in main
    max_d_reached = ts_max_d.max()  # Maximum distance reached by the pathogen
  File "/apps/developers/libraries/python-libs/3.1.0/1/python-3.6.5/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
